### ISSUE TITLE
manually editing the toml can break it.

### ISSUE THREAD

**Issue by snsvrno** [snsvrno/lpsettings-rs#1]
If you put in the wrong escape characters in the toml settings, it will not load it and override it if you change a setting in the future.

Example
```toml
local-folder = "C:\\Users\\snsv\\Projects\\libraries"
local-folder = "C:\Users\snsv\Projects\lib"
```
The first is how a path should look, the second is if I copied it from the file browser. This would result in bad character escapes and lpsetting from failing to load the toml, which them means it starts with a blank toml.

Put an error message if it can find the file but not load it so the user knows that they should check if for errors.
